const _prefix = "@films/";

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  LIST_FILM_NOW: _prefix + "LIST_FILM_NOW",
  LIST_FILM_NOW_SUCCESS: _prefix + "LIST_FILM_NOW_SUCCESS",
  LIST_FILM_FUTURE: _prefix + "LIST_FILM_FUTURE",
  LIST_FILM_FUTURE_SUCCESS: _prefix + "LIST_FILM_FUTURE_SUCCESS",
  POST_BOOKING_INFO: _prefix + "POST_BOOKING_INFO",
  POST_BOOKING_INFO_SUCCESS: _prefix + "POST_BOOKING_INFO_SUCCESS",
  FILM_DETAIL: _prefix + "FILM_DETAIL",
  FILM_DETAIL_SUCCESS: _prefix + "FILM_DETAIL_SUCCESS",
  LIST_FILM_TODAY: _prefix + "LIST_FILM_TODAY",
  LIST_FILM_TODAY_SUCCESS: _prefix + "LIST_FILM_TODAY_SUCCESS",
  LIST_SEATS: _prefix + "LIST_SEATS",
  LIST_SEATS_SUCCESS: _prefix + "LIST_SEATS_SUCCESS",
  SEARCH: _prefix + "SEARCH",
  SEARCH_SUCCESS: _prefix + "SEARCH_SUCCESS",
  COMMENT: _prefix + "COMMENT",
  COMMENT_SUCCESS: _prefix + "COMMENT_SUCCESS",
  PAYMENT_MOMO: _prefix + "PAYMENT_MOMO",
  PAYMENT_MOMO_SUCCESS: _prefix + "PAYMENT_MOMO_SUCCESS",
  CREATE_COMMENT: _prefix + "CREATE_COMMENT",
  CREATE_COMMENT_SUCCESS: _prefix + "CREATE_COMMENT_SUCCESS",
  LOADING_SHOW: _prefix + 'LOADING_SHOW',
  LOADING_HIDE: _prefix + 'LOADING_HIDE'
};
